config/routes.rb
Rails.application.routes.draw do

  resources :articles do
  	resources :comments
  end

  get 'gifs/gif_search'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 1}
	validates :text, presence: true, length: {minimum: 1}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true, length: { minimum: 1}
  validates :body, presence: true, length: {minimum: 1}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
		@article = Article.new
	end
	def index
		@articles = Article.all
	end
	def create
	  @article = Article.new(article_params)
	 
	  if @article.save
	  	redirect_to @article
	  else
	  	render 'new'
	  end 
	end
	def edit
		@article = Article.find(params[:id])
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new(article_id: @article.id)
	end
	def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
  	end
  	def destroy
  		@article = Article.find(params[:id])
  		@article.destroy

  		redirect_to articles_path
  	end
 
	private
	  def article_params
	    params.require(:article).permit(:title, :text)
  		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@article = Article.find(params[:article_id])
		@comment = Comment.new
	end
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		if @comment.save
			redirect_to article_path(@article)
		else
			render "edit"
		end
	end
	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end
	def edit
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
	end

	def update
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		if @comment.update(comment_params)
			redirect_to @article
		else
			render "edit"
		end
	end
	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

	def gif_search

	end





end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :Favorite_Chip_Flavor %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit "Submit or Forever Hold Your Peace"%>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Changing your Opinion?</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Opinions</h1>
<%= link_to 'Have an Opinion? Click to fill out a form', new_article_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Best Flavor of Chips</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to "Delete", article_path(article),
               method: :delete,
               data:{ confirm: "Are you sure you're wrong?"} %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Chips Ahoy!</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Favorite Flavor:</strong>
  <%= @article.text %>
</p>
<h2>Comments</h2>
<%= render @article.comments %>


<%#= render 'comments/form' %>
<%= link_to "Add Comment", new_article_comment_path(@article) %>
<%= link_to 'Back', articles_path %>
<%= link_to 'Edit', edit_article_path(@article) %>

app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Opinion:</strong>
  <%= comment.body %>
</p>
<p>

</p>
	<%=link_to 'Edit', edit_article_comment_path(id: comment.id, article_id: comment.article.id)%>
<p>
	<%= link_to "Delete Comment", [comment.article, comment],
				 method: :delete,
				 data: { confirm: "Are you sure?"} %>
</p>

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :Opinion_of_your_opinion %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Let the debate begin" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Changing your Comment?</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Ready to Comment?</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/gifs/gif_search.html.erb
<h1> Ready to Search for GIFS? </h1>

<%= form_tag("/posts") do %>
  <%= label_tag(:q, "What GIF are you looking for?") %>
  <br>
	  <%= text_field_tag(:q) %>
	  <%= submit_tag("Search") %>
	</br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to my Practice Site</h1>
<p>I go to Duke University and have an unhealthy obsession with Flaming Hot Cheetos</p>
<%= link_to 'Chip Opinions', controller: 'articles' %>
<%= link_to 'GIFFFFFS',  gifs_gif_search_path %>